# This is a basic workflow to help you get started with Actions

name: ProjectBuild-Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare build environment
        uses: gcarreno/setup-lazarus@v3.0.16
        with:
          lazarus-version: "2.0.12"
          include-packages: ""
      - name: Build application
        run: lazbuild DebtControl.lpi
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: |
            DebtControl
